name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
    steps:
    - uses: actions/checkout@v2
    
    - name: Install xorg-dev
      run: sudo apt install xorg-dev
      
    - name: Xvfb
      run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
